# -*- coding: utf-8 -*-
"""MachineLearning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14VHsIDPNdsLgnoQkM5ECEyVqbjrUG_wU
"""

import pandas as pd

"""Importar um base de dados"""

from google.colab import drive
drive.mount('/content/drive')

import os

# Listar arquivos na pasta principal do Google Drive
os.listdir('/content/drive/My Drive/')

