# -*- coding: utf-8 -*-
"""Testando

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14VHsIDPNdsLgnoQkM5ECEyVqbjrUG_wU
"""

import pandas as pd

"""Importar um base de dados"""

from google.colab import drive
drive.mount('/content/drive')

import os

# Listar arquivos na pasta principal do Google Drive
os.listdir('/content/drive/My Drive/')

base = pd.read_csv('/content/drive/My Drive/Pandas/titanic_train.csv')
base

#visualizar as 5 primeiras linhas
base.head()

#visualizar as ultimas 5 linhas
base.tail()

#visualizar o tamanho ////shape é um atributo
base.shape

display(base)

base.dtypes

base.info()

base.isnull().sum()

"""Conceitos Estatísticos"""

dados = {
    'X' : [2,1,6]
}
dados = pd.DataFrame(dados)

dados.mean() #media

dados.count() #quantidade

dados.median() #mediana #coloca os numeros em ordem crescente e soma os do meio

dados.std() #desvio padrão

dados.describe() #mostra tudo

base.describe()

base[['Survived','Sex','Age']]

base.Survived.value_counts()

base[base.Fare>500]

base[(base.Parch > 1) & (base.SibSp > 1)].head()

#buscar em um intervalo
base.iloc[30:40]

base.iloc[30:40, 0:3]

base.Fare.hist(bins=100)

base.Pclass.plot.bar()

base.Pclass.value_counts().plot.bar()